server:
  port: 8090
  forward-headers-strategy: framework
  error:
    include-exception: false
    include-binding-errors: always
    include-message: always
    include-stacktrace: never
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

api-docs:
  description: Department Employee API v1.0
  license-url: http://springdoc.org
  title: Department Rest API
  version: 1.0
  terms-of-service-url: http://swagger.io/terms/
  license: Apache 2.0

spring:
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: jdbc:h2:mem:department
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

organization:
  service:
    url: http://localhost:8091